### PR TITLE
.NET Standard Support (develop branch)

### PR DESCRIPTION
**Pull request by gentledepp**
This is a copy of PR #12 but re-targeted to the develop branch.

### CODE REVIEW

**Comment by jzeferino** [comment]
@gentledepp  will test this asap. thanks.

**Comment by jzeferino** [comment]
I've run the tests and the build and it worked. I will merge it to develop. Probably will release a version of it soon.

**Comment by gentledepp** [comment]
awesome! :-)

**Comment by jzeferino** [comment]
thank you for the work!

**Pull request merged**
